### ISSUE TITLE
swagger type seems to be incorrect

### ISSUE THREAD

**Issue by thomasyu888** [nlpsandbox/data-node-client#1]
```
    swagger_types = {
        'name': 'str',
        'annotation_source': 'CommonscomponentsschemasAnnotationSourceYaml',
        'text_date_annotations': 'list[CommonscomponentsschemasTextDateAnnotationYaml]',
        'text_person_name_annotations': 'list[CommonscomponentsschemasTextPersonNameAnnotationYaml]',
        'text_physical_address_annotations': 'list[CommonscomponentsschemasTextPhysicalAddressAnnotationYaml]'
    }
```

**Comment by thomasyu888** [comment]
My guess is that it has a hard time converting these paths: https://github.com/nlpsandbox/nlpsandbox-schemas/blob/develop/openapi/commons/components/schemas/Annotation.yaml

**Comment by thomasyu888** [comment]
Swagger has a hard time using the nested references..  Taking Annotation.yaml for an example, once I did this:

```
type: object
description: An annotation record
properties:
  name:
    description: Resource name of the annotation record, of the form datasets/{datasetId}/annotationStores/{annotationStoreId}/annotations/{annotationId}
    type: string
    readOnly: true
  annotationSource:
    type: object
    description: The source of an annotation record
    properties:
      resourceSource:
        type: object
        description: An API resource source
        properties:
          name:
            description: Full path of an API resource
            type: string
  textDateAnnotations:
    description: Date annotations in a text
    type: array
    items:
      $ref: TextDateAnnotation.yaml
  textPersonNameAnnotations:
    description: Person name annotations in a text
    type: array
    items:
      $ref: TextPersonNameAnnotation.yaml
  textPhysicalAddressAnnotations:
    description: Physical address annotations in a text
    type: array
    items:
      $ref: TextPhysicalAddressAnnotation.yaml
```

The swagger_types changed to:

```
    swagger_types = {
        'name': 'str',
        'annotation_source': 'object',
        'text_date_annotations': 'list[CommonscomponentsschemasTextDateAnnotationYaml]',
        'text_person_name_annotations': 'list[CommonscomponentsschemasTextPersonNameAnnotationYaml]',
        'text_physical_address_annotations': 'list[CommonscomponentsschemasTextPhysicalAddressAnnotationYaml]'
    }
```
